askcompany/askcompany/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG: 
    import debug_toolbar
    urlpatterns += [ 
        path('__debug__/', include(debug_toolbar.urls)), 
    ]

askcompany/blog/urls.py
from django.urls import path

app_name = 'blog'

urlpatterns = [
   
]

askcompany/shop/urls.py
from django.urls import path, register_converter
from .converters import FourDigitYearConverter
from . import views

app_name = 'shop'

register_converter(FourDigitYearConverter, 'yyyy')

urlpatterns = [
    path('articles/<yyyy:year>', views.year_archive, name='archives_year'),
    path('excel/', views.response_excel),
    path('', views.item_list, name='item_list'),
    path('<int:pk>/', views.item_detail, name='item_detail'),
    path('new/', views.item_new, name='item_new'),
    path('<int:pk>/edit/', views.item_edit, name='item_edit'),
]

askcompany/blog/models.py
from django.conf import settings
from django.db import models
from askcompany.utils import uuid_upload_to

class Post(models.Model):
    author_name = models.CharField(max_length=20)
    title = models.CharField(max_length=100)
    content = models.TextField()
    photo = models.ImageField(upload_to=uuid_upload_to)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    message = models.TextField()

askcompany/shop/models.py
from django.conf import settings
from django.db import models
from askcompany.utils import uuid_upload_to
from django.urls import reverse

class Item(models.Model):
    name = models.CharField(max_length=100)
    desc = models.TextField(blank=True)
    price = models.PositiveIntegerField()
    photo = models.ImageField(blank=True, upload_to=uuid_upload_to)
    is_publish = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'<{self.pk}> {self.name}'
    
    def get_absolute_url(self):
        return reverse('shop:item_detail', kwargs={'pk':self.pk})

    class Meta:
        ordering = ['id']

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

askcompany/shop/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'

askcompany/shop/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse
from django.views.generic import CreateView, UpdateView
from urllib.parse import quote
import os
from .models import Item
from .forms import ItemForm
import re

# Create your views here.
def year_archive(request, year):
    return HttpResponse('{}에 대한 내용'.format(year))

def response_excel(request):
    filepath = 'C:\\Users\\enhh\\Desktop\\excel_test.xlsx'
    filename = os.path.basename(filepath)

    with open(filepath, 'rb') as f:
        response = HttpResponse(f, content_type='application/vnd.ms-excel')

        encoded_filename = quote(filename)
        response['Content-Disposition'] = "attachment; filename*=utf-8''{}".format(encoded_filename)

        return response
    
def item_list(request):
    qs = Item.objects.all()

    q = request.GET.get('q', '')
    if q:
        qs = qs.filter(name__icontains=q)
    return render(request, 'shop/item_list.html', {
        'item_list':qs,
        'q':q,
    }

    )

def item_detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    return render(request, 'shop/item_detail.html', {
        'item' : item,  
    })

#def item_new(request, item=None):
#    if request.method == 'POST':
#        form = ItemForm(request.POST, request.FILES, instance=item)
#        if form.is_valid():
#            form.save()
#            redirect(item)
#    else:
#        form = ItemForm(instance=item)
#
#    return render(request, 'shop/item_form.html', {
#        'form':form,
#    })

#def item_edit(request, pk):
#    item = get_object_or_404(Item, pk=pk)
#    return item_new(request, item)
item_new = CreateView.as_view(model=Item, form_class=ItemForm)
item_edit = UpdateView.as_view(model=Item, form_class=ItemForm)

askcompany/askcompany/templates/layout.html
{% load static fresh_static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Ask company{% endblock %}</title>
    {% block extra_head %}
    <link rel="stylesheet" href="{% fresh_static 'main.css' %}">
    {% endblock %}
</head>
<body>
    <h1>Ask Company</h1>
    
    {% block content%}
    {% endblock %}

    <hr>
    &copy; 2021; Ask company

    {% block extra_body %}
        <script src="{% static 'main.js' %}"></script>
    {% endblock %}
</body>
</html>

askcompany/blog/templates/blog/layout.html
{% extends "layout.html" %}
{% load fresh_static %}

{% block title %}Blog by Ask company{% endblock %}

{% block extra_head %} 
    {{block.super}}
    <link rel="stylesheet" href="{% static 'blog/blog.css' %}">
{% endblock %}

{% block extra_body %}
    {{block.super}}
{% endblock %}

askcompany/shop/templates/shop/item_detail.html
{% extends "shop/layout.html" %}
{% load humanize %}

{% block content%}
    <h2>{{item.name}}</h2>

    {% if item.photo %}
        <img src="{{item.photo.url}}" style="max-width: 100;">
    {% endif %}

    가격: {{item.price|intcomma}}

    {% if item.desc %}
    <p>
        {{item.desc}}
    </p>
    {% endif %}

    <hr>
    <a href="{% url 'shop:item_list' %}">목록</a>
    <a href="{% url 'shop:item_edit' item.pk %}">수정</a>

{% endblock %}

askcompany/shop/templates/shop/item_form.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <title></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
    </head>
    <body>
        <div class="container">
            <div class="col-sm-12">

                <h2>New Item</h2>

                {% if error_list %}
                    <div class="alert alert-danger">
                        error_list: {{ error_list }}
                    </div>
                {% endif %}

                {% if initial %}
                    <div class="alert alert-info">
                        initial: {{ initial }}
                    </div>
                {% endif %}

                <form action="" method="post" enctype="multipart/form-data" autocomplete="off">
                    {% csrf_token %}

                    <table class="table table-bordered">
                        {{form.as_table}}
                    </table>

                    <input type="submit" value="저장하기" class="btn btn-primary" />
                </form>

            </div>
        </div>
    </body>
</html>

askcompany/shop/templates/shop/item_list.html
{% extends "shop/layout.html" %}

{% block content%}
<form action="" method="GET">
    <input type="text" name="q" value="{{q}}">
    <input type="submit" value="검색">
</form>
<hr/>
{{ block.super}}
<ul>
    {% for item in item_list %}
    <li>
        <a href="{{item.get_absolute_url}}">{{item.name}}</a>
        {{item.price}}
        {{item.desc}}
    </li>
    {% endfor %}
</ul>

<hr>
<a href="{% url 'shop:item_new' %}">New Item</a>
{% endblock %}

askcompany/shop/templates/shop/layout.html
{% extends "layout.html" %}
{% load fresh_static %} 

{% block title %}Shop by Ask company{% endblock %}

{% block extra_head %} 
    {{block.super}}
    <link rel="stylesheet" href="{% fresh_static 'shop/shop.css' %}">
{% endblock %}

{% block extra_body %}
    {{block.super}}
{% endblock %}